// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6seo5eSkIpp1-Dm_vZ5YsPJ-M2wO-rsc',
    appId: '1:265081638934:web:ff0361657a223175e7a537',
    messagingSenderId: '265081638934',
    projectId: 'nodered-c751f',
    authDomain: 'nodered-c751f.firebaseapp.com',
    databaseURL: 'https://nodered-c751f-default-rtdb.firebaseio.com',
    storageBucket: 'nodered-c751f.appspot.com',
    measurementId: 'G-MFLXT27NK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNXWdJjVHxQENO7ClpnwTpHr6fZ3zyJjg',
    appId: '1:265081638934:android:c9197b733bef6b5be7a537',
    messagingSenderId: '265081638934',
    projectId: 'nodered-c751f',
    databaseURL: 'https://nodered-c751f-default-rtdb.firebaseio.com',
    storageBucket: 'nodered-c751f.appspot.com',
  );
}
